/**
 * Generates PostgreSQL Row Level Security SQL for every tenant-owned table.
 *
 * A table is tenant-owned when its Prisma model has a `businessId` field.
 * Policies allow a row when EITHER
 *   • app.bypass_rls = 'on'                       (platform admin / system jobs), OR
 *   • businessId = app.current_business_id        (tenant-scoped client), OR
 *   • (nullable businessId only) businessId IS NULL AND app.allow_platform_rows = 'on'
 *
 * Usage:  pnpm db:rls > prisma/migrations/<timestamp>_rls/migration.sql
 * Re-run after adding new tenant models and commit the new migration.
 */
import { Prisma } from "@prisma/client";

const models = Prisma.dmmf.datamodel.models;

const lines: string[] = [];
lines.push("-- Row Level Security for tenant-owned tables. Generated by scripts/generate-rls.ts");
lines.push("");
lines.push(`CREATE OR REPLACE FUNCTION app_current_business_id() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.current_business_id', true), '')::uuid
$$;`);
lines.push("");
lines.push(`CREATE OR REPLACE FUNCTION app_rls_bypassed() RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT COALESCE(current_setting('app.bypass_rls', true), '') = 'on'
$$;`);
lines.push("");

for (const model of models) {
  const field = model.fields.find((f) => f.name === "businessId" && f.kind === "scalar");
  if (!field) continue;
  const table = model.dbName ?? model.name;
  const nullable = !field.isRequired;
  const predicate = nullable
    ? `app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on')`
    : `app_rls_bypassed() OR ("businessId" = app_current_business_id())`;
  lines.push(`-- ${model.name}`);
  lines.push(`ALTER TABLE "${table}" ENABLE ROW LEVEL SECURITY;`);
  lines.push(`ALTER TABLE "${table}" FORCE ROW LEVEL SECURITY;`);
  lines.push(`DROP POLICY IF EXISTS tenant_isolation ON "${table}";`);
  lines.push(`CREATE POLICY tenant_isolation ON "${table}"`);
  lines.push(`  USING (${predicate})`);
  lines.push(`  WITH CHECK (${predicate});`);
  lines.push("");
}

process.stdout.write(lines.join("\n") + "\n");
