-- Row Level Security for tenant-owned tables. Generated by scripts/generate-rls.ts

CREATE OR REPLACE FUNCTION app_current_business_id() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.current_business_id', true), '')::uuid
$$;

CREATE OR REPLACE FUNCTION app_rls_bypassed() RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT COALESCE(current_setting('app.bypass_rls', true), '') = 'on'
$$;

-- BusinessLocation
ALTER TABLE "business_locations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_locations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "business_locations";
CREATE POLICY tenant_isolation ON "business_locations"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- BusinessMembership
ALTER TABLE "business_memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_memberships" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "business_memberships";
CREATE POLICY tenant_isolation ON "business_memberships"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- BusinessSetting
ALTER TABLE "business_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_settings" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "business_settings";
CREATE POLICY tenant_isolation ON "business_settings"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Subscription
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "subscriptions";
CREATE POLICY tenant_isolation ON "subscriptions"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'));

-- BusinessDomain
ALTER TABLE "business_domains" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_domains" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "business_domains";
CREATE POLICY tenant_isolation ON "business_domains"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- BusinessTheme
ALTER TABLE "business_themes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_themes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "business_themes";
CREATE POLICY tenant_isolation ON "business_themes"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Page
ALTER TABLE "pages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pages";
CREATE POLICY tenant_isolation ON "pages"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- PageSection
ALTER TABLE "page_sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "page_sections" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "page_sections";
CREATE POLICY tenant_isolation ON "page_sections"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Revision
ALTER TABLE "revisions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "revisions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "revisions";
CREATE POLICY tenant_isolation ON "revisions"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- NavigationMenu
ALTER TABLE "navigation_menus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "navigation_menus" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "navigation_menus";
CREATE POLICY tenant_isolation ON "navigation_menus"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Redirect
ALTER TABLE "redirects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "redirects" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "redirects";
CREATE POLICY tenant_isolation ON "redirects"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Service
ALTER TABLE "services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "services" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "services";
CREATE POLICY tenant_isolation ON "services"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- ServiceArea
ALTER TABLE "service_areas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_areas" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "service_areas";
CREATE POLICY tenant_isolation ON "service_areas"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- ServiceAreaService
ALTER TABLE "service_area_services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_area_services" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "service_area_services";
CREATE POLICY tenant_isolation ON "service_area_services"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Material
ALTER TABLE "materials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "materials" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "materials";
CREATE POLICY tenant_isolation ON "materials"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- MediaFolder
ALTER TABLE "media_folders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "media_folders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "media_folders";
CREATE POLICY tenant_isolation ON "media_folders"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Media
ALTER TABLE "media" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "media" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "media";
CREATE POLICY tenant_isolation ON "media"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Project
ALTER TABLE "projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "projects" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "projects";
CREATE POLICY tenant_isolation ON "projects"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- ProjectMedia
ALTER TABLE "project_media" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "project_media" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "project_media";
CREATE POLICY tenant_isolation ON "project_media"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- ProjectService
ALTER TABLE "project_services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "project_services" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "project_services";
CREATE POLICY tenant_isolation ON "project_services"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- TeamMember
ALTER TABLE "team_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "team_members" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "team_members";
CREATE POLICY tenant_isolation ON "team_members"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Review
ALTER TABLE "reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reviews" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "reviews";
CREATE POLICY tenant_isolation ON "reviews"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- BusinessFeature
ALTER TABLE "business_features" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_features" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "business_features";
CREATE POLICY tenant_isolation ON "business_features"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- CustomFieldDefinition
ALTER TABLE "custom_field_definitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custom_field_definitions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "custom_field_definitions";
CREATE POLICY tenant_isolation ON "custom_field_definitions"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- CustomFieldValue
ALTER TABLE "custom_field_values" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custom_field_values" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "custom_field_values";
CREATE POLICY tenant_isolation ON "custom_field_values"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- PricingItem
ALTER TABLE "pricing_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pricing_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pricing_items";
CREATE POLICY tenant_isolation ON "pricing_items"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- PricingRule
ALTER TABLE "pricing_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pricing_rules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pricing_rules";
CREATE POLICY tenant_isolation ON "pricing_rules"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Customer
ALTER TABLE "customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "customers";
CREATE POLICY tenant_isolation ON "customers"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Lead
ALTER TABLE "leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "leads" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "leads";
CREATE POLICY tenant_isolation ON "leads"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Quote
ALTER TABLE "quotes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "quotes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "quotes";
CREATE POLICY tenant_isolation ON "quotes"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Form
ALTER TABLE "forms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "forms" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "forms";
CREATE POLICY tenant_isolation ON "forms"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- FormSubmission
ALTER TABLE "form_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "form_submissions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "form_submissions";
CREATE POLICY tenant_isolation ON "form_submissions"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Workflow
ALTER TABLE "workflows" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workflows" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "workflows";
CREATE POLICY tenant_isolation ON "workflows"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Job
ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "jobs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "jobs";
CREATE POLICY tenant_isolation ON "jobs"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- JobStageHistory
ALTER TABLE "job_stage_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_stage_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "job_stage_history";
CREATE POLICY tenant_isolation ON "job_stage_history"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Task
ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tasks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "tasks";
CREATE POLICY tenant_isolation ON "tasks"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Invoice
ALTER TABLE "invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoices" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "invoices";
CREATE POLICY tenant_isolation ON "invoices"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Payment
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "payments";
CREATE POLICY tenant_isolation ON "payments"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Booking
ALTER TABLE "bookings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bookings" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "bookings";
CREATE POLICY tenant_isolation ON "bookings"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- AutomationRule
ALTER TABLE "automation_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "automation_rules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "automation_rules";
CREATE POLICY tenant_isolation ON "automation_rules"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- AutomationRun
ALTER TABLE "automation_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "automation_runs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "automation_runs";
CREATE POLICY tenant_isolation ON "automation_runs"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- DomainEvent
ALTER TABLE "domain_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "domain_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "domain_events";
CREATE POLICY tenant_isolation ON "domain_events"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'));

-- Message
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "messages";
CREATE POLICY tenant_isolation ON "messages"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- Notification
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "notifications";
CREATE POLICY tenant_isolation ON "notifications"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'));

-- Integration
ALTER TABLE "integrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "integrations";
CREATE POLICY tenant_isolation ON "integrations"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'));

-- Webhook
ALTER TABLE "webhooks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhooks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "webhooks";
CREATE POLICY tenant_isolation ON "webhooks"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

-- ApiKey
ALTER TABLE "api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_keys" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "api_keys";
CREATE POLICY tenant_isolation ON "api_keys"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'));

-- AiProvider
ALTER TABLE "ai_providers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_providers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ai_providers";
CREATE POLICY tenant_isolation ON "ai_providers"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'));

-- AiUsage
ALTER TABLE "ai_usage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_usage" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ai_usage";
CREATE POLICY tenant_isolation ON "ai_usage"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'));

-- AuditLog
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "audit_logs";
CREATE POLICY tenant_isolation ON "audit_logs"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()) OR ("businessId" IS NULL AND COALESCE(current_setting('app.allow_platform_rows', true), '') = 'on'));

-- AnalyticsEvent
ALTER TABLE "analytics_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "analytics_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "analytics_events";
CREATE POLICY tenant_isolation ON "analytics_events"
  USING (app_rls_bypassed() OR ("businessId" = app_current_business_id()))
  WITH CHECK (app_rls_bypassed() OR ("businessId" = app_current_business_id()));

